### ISSUE TITLE
Crash when inflating ToggleGroup

### ISSUE THREAD

**Issue by richardleggett** [rcketscientist/ToggleButtons#12] opened 2019-02-01 16:21 UTC
Looks like RoundRectDrawable's constructor is package private (in androidx.cardview.widget.RoundRectDrawable) so we get illegal access from `ToggleGroupApi21`.

It is/was public in another branch (see diff):
https://android.googlesource.com/platform/frameworks/support/+/c42ba8c%5E!/

Error during inflate:

```
Caused by: java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ToggleGroupApi21' attempting to access 'androidx.cardview.widget.RoundRectDrawable' (declaration of 'androidx.appcompat.widget.ToggleGroupApi21' appears in /data/app/com.myapp-UPWcvdqmrM2341e2333333==/base.apk!classes2.dex)
        at androidx.appcompat.widget.ToggleGroupApi21.initialize(ToggleGroupApi21.java:17)
```

Related libraries in use:

``` 
implementation 'androidx.core:core-ktx:1.0.1'
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'androidx.appcompat:appcompat:1.0.2'
implementation 'androidx.fragment:fragment-ktx:1.0.0'
implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
implementation 'androidx.preference:preference:1.0.0'
implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha2' 
```

**Comment by rcketscientist** [comment] 2019-02-01 16:27
Are you on 9.0?  This wasn't an issue on an 8.0 device recently.  `package private` should be fine.  It may be that the package moved.  Hopefully, it's an easy fix since I'd rather not pull in those extra maintenance files.

**Comment by richardleggett** [comment] 2019-02-01 16:35
Hello, yes 9.0 here. Do you think the package moved? 

So we've got: `androidx.appcompat.widget.ToggleGroupApi21`
Accessing a package-private constructor in: `androidx.cardview.widget.RoundRectDrawable`

I tried to downgrade a few libraries to see if I could fix it (assuming the constructor was public previously as per the above diff) but I keep getting the same error.

**Comment by rcketscientist** [comment] 2019-02-01 17:10
That's the issue then.  I'll have to create `ToggleGroupApi28` which simply lives in `androidx.cardview`.

**Comment by richardleggett** [comment] 2019-02-01 17:14
Got you, sorry I had to leave the office or I would have been able to look more into a fix and PR. If you don't find time lemme know and I'll try to take a look over the weekend.

**Comment by rcketscientist** [comment] 2019-02-01 17:36
I'll be scrambling to find time as well.  If you get a chance to look and there isn't a patch or a post here then I haven't gotten to it.  It shouldn't be more than a few minutes effort (fingers crossed).

**Comment by rcketscientist** [comment] 2019-02-02 15:20
This can't be reproduced locally with an API 28 emulator on the sample.  Can you create a repro repo?

**Comment by rcketscientist** [comment] 2019-02-09 18:12
Closing until there's a way to reproduce.

**Closed as completed by rcketscientist** 2019-02-09 18:12 UTC
